# Rails loads items on shared keys for all environments
shared:
  - key: "eigenfocus-light"
    name: "Light"
  - key: "eigenfocus-dark"
    name: "Dark"
  # - key: "dim"
  #   name: "Light Dim"
  # - key: "spookyhalloween"
  #   name: "Spooky Halloween"
  # - key: "christmas"
  #   name: "Merry Christmas"
